### PR TITLE
Add Android support for progress-view

### PR DESCRIPTION
**Pull request by alpha0010**

### CODE REVIEW

**Comment by alpha0010** [comment]
@Naturalclar Have you had a chance to look at this?  It is low risk since it touches only android exclusive files (which likely no one is relying on, since it is unimplemented).

**Comment by Naturalclar** [comment]
@alpha0010 sorry for the late response! will take a look at this

**Review by Naturalclar — APPROVED** [review]
@alpha0010 this is working great! thanks so much for the addition!

**Comment by Naturalclar** [comment]
merged in #58 thanks so much!

**Pull request closed without merging**
