### PR TITLE
update ios header file so it'll work with expo sdk 44+

### PR DESCRIPTION
**Pull request by tran2**
The fix is based on fixes from this issue: https://github.com/expo/expo/issues/15649

### CODE REVIEW

**Comment by tran2** [comment]
upgraded slipper so that ios build would work

**Comment by Yandamuri** [comment]
@tran2 still facing the same issue https://github.com/expo/expo/issues/15649

I am using `"@react-native-community/progress-view": "1.3.1"

When would the change be merged?

**Comment by tran2** [comment]
@Naturalclar could you approve running the workflow to see if this fixes the ios build? Thanks!

**Comment by Yandamuri** [comment]
> > @Naturalclar could you approve running the workflow to see if this fixes the ios build? Thanks!
> 
> Any update on this? eagerly waiting for this update.

May I hear any update on this? 

I can proceed for further only if this progressView issue is resolved.

**Comment by Yandamuri** [comment]
> @Naturalclar could you approve running the workflow to see if this fixes the ios build? Thanks!

@Naturalclar @tran2 

May I hear any update on this? 

I can proceed for further in my project only if this `progress-view` issue is resolved.

**Comment by Naturalclar** [comment]
@Yandamuri @tran2 sorry for the late response, I've just approved the CI run

**Comment by Yandamuri** [comment]
> @Yandamuri @tran2 sorry for the late response, I've just approved the CI run

@Naturalclar Thank you so much for your prompt response🙂.

 May I know when will master branch be merged?

**Review by Naturalclar — APPROVED** [review]
LGTM!

**Comment by Yandamuri** [comment]
@Naturalclar  Thank you for approving the changes.

I have done changes in `/node_modules/@react-native-community/progress-view/ios/RNCProgressView.h` as per this [commit](https://github.com/react-native-progress-view/progress-view/commit/2519141ddea0b8c409ae86b0188825b3cffea307) and I can confirm that this commit resolves the issue.

Now, My doubt is which version of `@react-native-community/progress-view` resolves this? Because  **v1.3.1**  is still giving me the issue unless I do changes in `/node_modules/@react-native-community/progress-view/ios/RNCProgressView.h`.

**Comment by Yandamuri** [comment]
> @Naturalclar Thank you for approving the changes.
> 
> I have done changes in `/node_modules/@react-native-community/progress-view/ios/RNCProgressView.h` as per this [commit](https://github.com/react-native-progress-view/progress-view/commit/2519141ddea0b8c409ae86b0188825b3cffea307) and I can confirm that this commit resolves the issue.
> 
> Now, My doubt is which version of `@react-native-community/progress-view` resolves this? Because **v1.3.1** is still giving me the issue unless I do changes in `/node_modules/@react-native-community/progress-view/ios/RNCProgressView.h`.

@Naturalclar Can you please comment over this?

**Comment by Naturalclar** [comment]
@Yandamuri sorry for the late response. The fix is included in v1.3.2

**Pull request merged**
